# Generated by Django 4.2.3 on 2023-09-02 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='icon',
            new_name='instructor',
        ),
    ]
