# Generated by Django 4.2.3 on 2023-09-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_author_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discount',
        ),
    ]
