# Generated by Django 4.2.3 on 2023-09-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='Media/featured_img'),
        ),
    ]
